---

- name: Ensure RPM GPG key is present
  rpm_key:
    key: https://packagecloud.io/gpg.key
    state: present

- name: Ensure Zypper repository file exists
  get_url:
    url: "https://packagecloud.io/install/repositories/slacktechnologies/slack/config_file.repo?{{ slack_repo_query_string }}"
    dest: /etc/zypp/repos.d/slack.repo

- name: Ensure Slack is installed
  zypper:
    name: slack
    state: present
    update_cache: true
