---

controller_ansible_venv_site_packages: true
controller_ansible_galaxy_roles:
  - name: asciinema
    src: xanmanning.asciinema
  - name: awscli
    src: xanmanning.awscli
  - name: azurecli
    src: xanmanning.azurecli
  - name: diagrams
    src: xanmanning.diagrams
  - name: enpass
    src: xanmanning.enpass
    become: true
  - name: go
    src: xanmanning.go
  - name: slack
    become: true
  - name: sshuttle
    src: xanmanning.sshuttle
  - name: molecule
    src: xanmanning.molecule
  - name: netextender
    become: true
  - name: teams
    become: true
  - name: terraform
    src: xanmanning.terraform
  - name: vagrant
    src: xanmanning.vagrant
    become: true
  - name: virtualbox
    src: xanmanning.virtualbox
    become: true
  - name: vscode
    src: xanmanning.vscode
    become: true
  - name: rbenv
    src: zzet.rbenv
    become: true

controller_ansible_projects:
  - name: vagrant-cluster-playground
    repo: https://github.com/xmanningcentiq/vagrant-cluster-playground
    update_repo: true
    version:  master
    force: false
  - name: dotfiles
    repo: https://github.com/xanmanning/dotfiles.git
    update_repo: true
    version:  master
    force: false

rbenv:
  env: user
  version: v1.1.2
  default_ruby: 2.5.1
  rubies:
    - version: 2.5.1
    - version: 2.7.1

rbenv_users:
  - xmanning

molecule_version: 2.22.0

workstation_packages:
  - yum-cron
  - ca-certificates
  - kernel-headers
  - kernel-devel
  - curl
  - terminator
  - tmux
  - vim-X11
  - git
  - jq
  - python-pip
  - python3
  - python3-pip
  - ruby
  - ruby-devel
  - libffi-devel
  - sqlite-devel
  - rubygems
  - openssh-server
  - sshpass
  - mtr
  - chrony
  - gpaste
  - gpaste-applet
  - gnome-tweak-tool
  - gnome-shell-extension-common
  - gnome-shell-extension-gpaste
  - gnome-shell-extension-no-hot-corner
  - gstreamer-plugins-good
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-ugly-free
  - NetworkManager-openvpn
  - NetworkManager-openvpn-gnome
  - NetworkManager-vpnc
  - NetworkManager-vpnc-gnome
  - NetworkManager-openconnect
  - openconnect
  - vpnc
  - vpnc-script
  - java-1.8.0-openjdk
  - freerdp
  - vorbis-tools
  - gimp
  - thunderbird
  - filezilla
  - whois
  - zip
  - unzip
  - gnupg2
  - pwgen
  - pass
  - pandoc
  - texlive
  - wkhtmltopdf
  - ShellCheck
  - deja-dup
  - deja-dup-nautilus
  - graphviz
  - libXScrnSaver
  - lsof
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - gcc
  - bzip2
  - libyaml-devel
  - libffi-devel
  - gdbm-devel
  - ncurses-devel
  - openssl-devel
  - readline-devel
  - zlib-devel

workstation_pip_packages:
  - name: tmuxp
    version: 1.2.6

workstation_gem_packages:
  - name: bundler
    version: 2.0.2
  - name: cucumber
    version: 3.1.2
  - name: rspec
    version: 3.9.0

workstation_secureboot_enabled: false
