---

- name: Ensure RPM GPG key is present
  rpm_key:
    key: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- name: Ensure YUM repository file exists
  get_url:
    url: "https://packagecloud.io/install/repositories/slacktechnologies/slack/config_file.repo?{{ slack_repo_query_string }}"
    dest: /etc/yum.repos.d/slack.repo

- name: Ensure slack is installed (YUM)
  yum:
    name: slack
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "yum"

- name: Ensure Slack is installed (DNF)
  yum:
    name: slack
    state: present
    update_cache: true
  when: ansible_pkg_mgr == "dnf"
