---

controller_ansible_venv_site_packages: true
controller_ansible_galaxy_roles:
  - name: asciinema
    src: xanmanning.asciinema
  - name: awscli
    src: xanmanning.awscli
  - name: azurecli
    src: xanmanning.azurecli
  - name: diagrams
    src: xanmanning.diagrams
  - name: enpass
    src: xanmanning.enpass
    become: true
  - name: go
    src: xanmanning.go
  - name: kubectl
    src: xanmanning.kubectl
  - name: minikube
    src: xanmanning.minikube
  - name: slack
    become: true
  - name: sshuttle
    src: xanmanning.sshuttle
  - name: molecule
    src: xanmanning.molecule
  - name: netextender
    become: true
  - name: teams
    become: true
  - name: terraform
    src: xanmanning.terraform
  - name: vagrant
    src: xanmanning.vagrant
    become: true
  - name: virtualbox
    src: xanmanning.virtualbox
    become: true
  - name: vscode
    src: xanmanning.vscode
    become: true
  - name: rbenv
    src: zzet.rbenv
    become: true

controller_ansible_projects:
  - name: vagrant-cluster-playground
    repo: https://github.com/xmanningcentiq/vagrant-cluster-playground
    update_repo: true
    version:  master
    force: false
  - name: dotfiles
    repo: https://github.com/xanmanning/dotfiles.git
    update_repo: true
    version:  master
    force: false

rbenv:
  env: user
  version: v1.1.2
  default_ruby: 2.5.1
  rubies:
    - version: 2.5.1
    - version: 2.7.1

rbenv_users:
  - xmanning

sshuttle_version: 0.78.5

workstation_packages:
  - firefox
  - thunderbird
  - deja-dup
  - deja-dup-nautilus
  - gnome-tweaks
  - git
  - ruby
  - expect
  - mtr
  - chrony
  - graphviz
  - gimp
  - whois
  - vim
  - gvim
  - tmux
  - jq
  - libreswan
  - strongswan
  - strongswan-libipsec
  - NetworkManager-strongswan
  - NetworkManager-strongswan-gnome
  - vpnc
  - NetworkManager-vpnc
  - NetworkManager-vpnc-gnome
  - openconnect
  - NetworkManager-openconnect
  - NetworkManager-openconnect-gnome
  - sstp-client
  - NetworkManager-sstp
  - NetworkManager-sstp-gnome
  - wireguard-tools
  - zip
  - unzip
  - gnupg2
  - pwgen
  - chrome-gnome-shell
  - terminator
  - remmina
  - podman
  - podman-compose
  - podman-docker
  - gpaste
  - gpaste-ui
  - gnome-shell-extension-common
  - gnome-shell-extension-gpaste
  - gnome-shell-extension-no-topleft-hot-corner
  - gnome-shell-extension-topicons-plus
  - kernel-devel
  - gcc
  - make
  - perl
  - python3-devel
  - ShellCheck
  - libnsl
  - libnsl2
  - libnsl2-devel
  - vorbis-tools
  - virt-manager
  - libvirt-client
  #- https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

workstation_pip_packages:
  - name: tmuxp
    version: 1.2.6

workstation_gem_packages:
  - name: bundler
    version: 2.0.2
  - name: cucumber
    version: 3.1.2
  - name: rspec
    version: 3.9.0
  - name: travis
    version: 1.10.0

workstation_secureboot_enabled: true

virtualbox_skip_virtualization_test: "{{ true if ansible_virtualization_type == 'virtualbox' else false }}"
minikube_skip_virtualization_test: "{{ true if ansible_virtualization_type == 'virtualbox' else false }}"
