---

- name: Ensure Slack Repository key exists
  apt_key:
    url: https://packagecloud.io/slacktechnologies/slack/gpgkey
    state: present

- name: Ensure Apt repository file exists
  get_url:
    url: "https://packagecloud.io/install/repositories/slacktechnologies/slack/config_file.list?{{ slack_repo_query_string }}"
    dest: /etc/apt/sources.list.d/slack.list

- name: Ensure Slack is installed
  apt:
    name: slack
    state: present
    update_cache: true
